VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "ubuntu/trusty64"
	config.vm.network "forwarded_port", guest: 8000, host: 8000, auto_correct: true
	config.vm.provision :docker
	config.vm.provision :docker_compose, yml: "/vagrant/docker-compose.yml", run: "always", rebuild: true
end
